### ISSUE TITLE
Extra '/' in path on line 1062 of 'circle-blvd/server/app.js' causes ENOENT error during npm start

### ISSUE THREAD

**Issue by myersg86** [secret-project/circle-blvd#8]
Error Message:
 .../circle-blvd/server$ npm start

> circle-blvd@1.4.7 start /home/greg/Documents/circle-blvd/server
> node server.js

Express http server listening on port 3000

{ [Error: ENOENT, open '/home/greg/Documents/circle-blvd/web/public/_js//lib-app-services-controllers-main.js']
errno: -2,
code: 'ENOENT',
path: '.../circle-blvd/web/public/_js//lib-app-services-controllers-main.js' }

![localhost](https://cloud.githubusercontent.com/assets/9864446/8351510/9dbffeb0-1ae2-11e5-8d5f-bb7162e0436e.png)

**Comment by exclsr** [comment]
Fixed with pull request #12
